
export const Routes = {
    // pages
    Presentation: { path: "/" },
    DashboardOverview: { path: "/dashboard/overview" },
    Transactions: { path: "/transactions" },
    Settings: { path: "/settings" },
    Profile: { path: "/profile" },
    EditeProfile: { path: "/edite-profile" },
    Upgrade: { path: "/upgrade" },
    BootstrapTables: { path: "/tables/bootstrap-tables" },
    Athletes:{path: "/tables/Athletes"},
    Comp:{path: "/tables/Comp"},
    CompAdd:{path: "/tables/CompAdd"},
    CompUpd:{path: "/tables/CompUpd"},
    CompCons:{path: "/tables/CompCons"},

    updphotos:{path: "/tables/updphotos"},
    photosent:{path: "/tables/photosent"},
    photosarb:{path: "/tables/photosarb"},
    ArUpd:{path: "/tables/ArUpd"},

    EntUpd:{path: "/tables/EntUpd"},

    AthleteUpd:{path: "/tables/AthleteUpd"},
    LicenceUpd:{path: "/tables/LicenceUpd"},
    ClubUpd:{path: "/tables/ClubUpd"},

    SuppAdd:{path: "/tables/SuppAdd"},
    PoidsAdd:{path: "/tables/PoidsAdd"},
    AgeAdd:{path: "/tables/AgeAdd"},
    Sportadd:{path: "/tables/Sportadd"},

    ArAdd:{path: "/tables/ArrAdd"},
    Supporteur:{path: "/tables/Supporteur"},
    SaisonAdd:{path: "/tables/SaisonAdd"},
    LigueAdd:{path: "/tables/LigueAdd"},
    Arbitre:{path: "/tables/Arbitre"},
    Entraineur:{path: "/tables/Entraineur"},
    EntAdd:{path: "/tables/EntAdd"},
    Saison:{path: "/tables/Saison"},
    Age:{path: "/tables/age"},
    Poids:{path: "/tables/Poids"},
    Athleteadd:{path: "/tables/Athleteadd"},
    Clubs:{path: "/tables/Clubs"},
    Ligue:{path: "/tables/Ligue"},

    ClubAdd:{path: "/tables/ClubAdd"},
    Sports:{path: "/tables/Sports"},
    Licence:{path: "/tables/Licence"},
    LicenceAdd:{path: "/tables/LicenceAdd"},
    Billing: { path: "/examples/billing" },
    Invoice: { path: "/examples/invoice" },
    Signin: { path: "/examples/sign-in" },
    Signinadmin: { path: "/admin/sign-in" },
    Signup: { path: "/examples/sign-up" },
    Role: { path: "/examples/Role" },
    ForgotPassword: { path: "/examples/forgot-password" },
    ResetPassword: { path: "/examples/reset-password" },
    Lock: { path: "/examples/lock" },
    NotFound: { path: "/examples/404" },
    ServerError: { path: "/examples/500" },

    // docs
    DocsOverview: { path: "/documentation/overview" },
    DocsDownload: { path: "/documentation/download" },
    DocsQuickStart: { path: "/documentation/quick-start" },
    DocsLicense: { path: "/documentation/license" },
    DocsFolderStructure: { path: "/documentation/folder-structure" },
    DocsBuild: { path: "/documentation/build-tools" },
    DocsChangelog: { path: "/documentation/changelog" },

    // components
    Accordions: { path: "/components/accordions" },
    Alerts: { path: "/components/alerts" },
    Badges: { path: "/components/badges" },
    Widgets: { path: "/widgets" },
    Breadcrumbs: { path: "/components/breadcrumbs" },
    Buttons: { path: "/components/buttons" },
    Forms: { path: "/components/forms" },
    Modals: { path: "/components/modals" },
    Navs: { path: "/components/navs" },
    Navbars: { path: "/components/navbars" },
    Pagination: { path: "/components/pagination" },
    Popovers: { path: "/components/popovers" },
    Progress: { path: "/components/progress" },
    Tables: { path: "/components/tables" },
    Tabs: { path: "/components/tabs" },
    Tooltips: { path: "/components/tooltips" },
    Toasts: { path: "/components/toasts" },
    WidgetsComponent: { path: "/components/widgets" }
};